// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsNTDqmawc3P6i5TEvHh26AXoAbx_DdXU',
    appId: '1:316418790596:web:697927319361a861ebe591',
    messagingSenderId: '316418790596',
    projectId: 'banana-keraton',
    authDomain: 'banana-keraton.firebaseapp.com',
    storageBucket: 'banana-keraton.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEuK9uDttXZ6u-_iKrOALvCi64GlIkWTo',
    appId: '1:316418790596:android:84e5088c06ba993cebe591',
    messagingSenderId: '316418790596',
    projectId: 'banana-keraton',
    storageBucket: 'banana-keraton.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALwo-Z0qB4tDTk6HFhoMBB5alows4B-YM',
    appId: '1:316418790596:ios:33f5fc75b157e78debe591',
    messagingSenderId: '316418790596',
    projectId: 'banana-keraton',
    storageBucket: 'banana-keraton.appspot.com',
    iosBundleId: 'com.example.uaskelompokPam',
  );
}
